/*
 * eIsland - A sleek, Apple Dynamic Island inspired floating widget for Windows, built with Electron.
 * https://github.com/JNTMTMTM/eIsland
 *
 * Copyright (C) 2026 JNTMTMTM
 * Copyright (C) 2026 pyisland.com
 *
 * Original author: JNTMTMTM[](https://github.com/JNTMTMTM)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**
 * @file index.test.ts
 * @description 验证真实主进程入口的启动接线、协议安全、快捷键、窗口和退出生命周期。
 * @author 鸡哥
 */

import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import Module from 'node:module';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import windowMock from '../window/test/windowMock';
import type { Mock } from 'vitest';
type FunctionMock = Mock<(...args: unknown[]) => unknown>;
type OptionBag = Record<string, unknown>;
type Callback = (...args: unknown[]) => unknown;
interface MainWindowFixture extends ReturnType<typeof windowMock> { getBounds: () => { x: number; y: number; width: number; height: number }; }
const mocks = vi.hoisted(() => ({
  functions: new Map<string, FunctionMock>(),
  events: new Map<string, Callback>(),
  handlers: new Map<string, Callback>(),
  protocols: new Map<string, Callback>(),
  boot: undefined as (() => void) | undefined,
  main: undefined as MainWindowFixture | undefined,
  windows: [] as ReturnType<typeof createGlowWindow>[],
  lock: true, packaged: true,
  firstLaunch: false, startupAnimation: true,
  modeFiles: new Map<string, unknown>(),
  runtime: new Map<string, { payload: { isPlaying: boolean } }>(),
  whitelist: true,
}));
function leaf(name: string): FunctionMock {
  const existing = mocks.functions.get(name);
  if (existing) return existing;
  const spy = vi.fn<(...args: unknown[]) => unknown>();
  mocks.functions.set(name, spy);
  return spy;
}
function factory(name: string, variable: string, methods: string[]): FunctionMock {
  const service = Object.fromEntries(methods.map((method) => [method, leaf(`${variable}.${method}`)]));
  return leaf(name).mockReturnValue(service);
}
function options(name: string): OptionBag { const [[value]] = leaf(name).mock.calls; expect(value).toBeTypeOf('object'); return value as OptionBag; }
function call(value: OptionBag, name: string, ...args: unknown[]): unknown { const callback = value[name]; expect(callback).toBeTypeOf('function'); return (callback as Callback)(...args); }
function platform(value: string) { const double = Object.create(process) as NodeJS.Process; Object.defineProperty(double, 'platform', { value }); vi.stubGlobal('process', double); }
function createGlowWindow() { const win = windowMock(); return Object.assign(win, { webContents: Object.assign(win.webContents, { executeJavaScript: vi.fn<(script: string) => Promise<void>>(() => Promise.resolve()) }) }); }
function constructGlowWindow() { const win = createGlowWindow(); mocks.windows.push(win); return win; }
const electron = {
  app: {
    get isPackaged() { return mocks.packaged; },
    requestSingleInstanceLock: () => mocks.lock,
    quit: leaf('app.quit'),
    getPath: leaf('app.getPath'),
    getAppPath: leaf('app.getAppPath'),
    getVersion: leaf('app.getVersion'),
    on: (name: string, callback: Callback) => { mocks.events.set(name, callback); },
    whenReady: () => ({ then: (callback: () => void) => { mocks.boot = callback; } }),
  },
  BrowserWindow: Object.assign(vi.fn(constructGlowWindow), { getAllWindows: leaf('BrowserWindow.getAllWindows') }),
  globalShortcut: { unregisterAll: leaf('globalShortcut.unregisterAll') },
  protocol: { registerSchemesAsPrivileged: leaf('protocol.registerSchemesAsPrivileged'), handle: (name: string, callback: Callback) => { mocks.protocols.set(name, callback); } },
  net: { fetch: leaf('net.fetch') },
  ipcMain: { handle: (name: string, callback: Callback) => { mocks.handlers.set(name, callback); } },
  screen: { getDisplayMatching: leaf('screen.getDisplayMatching'), getPrimaryDisplay: leaf('screen.getPrimaryDisplay') },
};
vi.mock('electron', () => electron);
vi.mock('fs', () => ({ existsSync: leaf('existsSync'), mkdirSync: leaf('mkdirSync'), readFileSync: leaf('readFileSync'), writeFileSync: leaf('writeFileSync') }));
vi.mock('@electron-toolkit/utils', () => ({ electronApp: { setAppUserModelId: leaf('setAppUserModelId') }, optimizer: { watchWindowShortcuts: leaf('watchWindowShortcuts') } }));
vi.mock('electron-updater', () => ({ autoUpdater: { marker: 'updater' } }));
vi.mock('../config/storeConfig', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../config/storeConfig')>();
  const overrideNames = Object.keys(actual).filter((name) => /^(read|write)/.test(name));
  return { ...actual, ...Object.fromEntries(overrideNames.map((name) => [name, leaf(name)])) };
});
vi.mock('../tray', () => ({ createTray: leaf('createTray'), destroyTray: leaf('destroyTray'), toggleTray: leaf('toggleTray') }));
vi.mock('../log/mainLog', () => ({ createSessionMainLogger: leaf('createSessionMainLogger') }));
vi.mock('../clipboard/urlWatcher', () => ({ startClipboardUrlWatcher: leaf('startClipboardUrlWatcher'), stopClipboardUrlWatcher: leaf('stopClipboardUrlWatcher') }));
vi.mock('../clipboard/clipboardUrlState', () => ({ createClipboardUrlState: factory('createClipboardUrlState', 'clipboardUrlState', ['getBlacklist', 'getDetectMode', 'getMonitorEnabled', 'setBlacklist', 'setDetectMode', 'setMonitorEnabled']) }));
vi.mock('../ipc/agent/claudeCodeStatusIpc', () => ({ registerClaudeCodeStatusIpcHandlers: leaf('registerClaudeCodeStatusIpcHandlers') }));
vi.mock('../ipc/agent/codexStatusIpc', () => ({ registerCodexStatusIpcHandlers: leaf('registerCodexStatusIpcHandlers') }));
vi.mock('../ipc/settings/clipboard', () => ({ registerClipboardIpcHandlers: leaf('registerClipboardIpcHandlers') }));
vi.mock('../ipc/window/capture', () => ({ registerCaptureIpcHandlers: leaf('registerCaptureIpcHandlers') }));
vi.mock('../services/captureLocalOcrService', () => ({ disposeLocalOcrWorker: leaf('disposeLocalOcrWorker') }));
vi.mock('../ipc/system/screenshotHotkey', () => ({ registerScreenshotHotkeyIpcHandlers: leaf('registerScreenshotHotkeyIpcHandlers') }));
vi.mock('../ipc/app/app', () => ({ registerAppIpcHandlers: leaf('registerAppIpcHandlers') }));
vi.mock('../ipc/system/system', () => ({ registerSystemIpcHandlers: leaf('registerSystemIpcHandlers') }));
vi.mock('../ipc/app/updater', () => ({ registerUpdaterIpcHandlers: leaf('registerUpdaterIpcHandlers') }));
vi.mock('../ipc/app/download', () => ({ registerDownloadIpcHandlers: leaf('registerDownloadIpcHandlers') }));
vi.mock('../ipc/app/imageCompression', () => ({ registerImageCompressionIpcHandlers: leaf('registerImageCompressionIpcHandlers') }));
vi.mock('../ipc/window/wallpaper', () => ({ registerWallpaperIpcHandlers: leaf('registerWallpaperIpcHandlers') }));
vi.mock('../ipc/media/wallpaperVideo', () => ({ registerWallpaperVideoIpcHandlers: leaf('registerWallpaperVideoIpcHandlers') }));
vi.mock('../ipc/app/formatFactory', () => ({ registerFormatFactoryIpcHandlers: leaf('registerFormatFactoryIpcHandlers') }));
vi.mock('../ipc/app/net', () => ({ registerNetIpcHandlers: leaf('registerNetIpcHandlers') }));
vi.mock('../ipc/app/mail', () => ({ registerMailIpcHandlers: leaf('registerMailIpcHandlers') }));
vi.mock('../ipc/app/store', () => ({ registerStoreIpcHandlers: leaf('registerStoreIpcHandlers') }));
vi.mock('../media/albumMedia', () => ({ handleAlbumMediaRequest: leaf('handleAlbumMediaRequest') }));
vi.mock('../ipc/app/log', () => ({ registerLogIpcHandlers: leaf('registerLogIpcHandlers') }));
vi.mock('../ipc/media/music', () => ({ registerMusicIpcHandlers: leaf('registerMusicIpcHandlers') }));
vi.mock('../ipc/media/musicProviderAuth', () => ({ registerMusicProviderAuthIpcHandlers: leaf('registerMusicProviderAuthIpcHandlers') }));
vi.mock('../ipc/media/qishui', () => ({ registerQishuiBusinessIpcHandlers: leaf('registerQishuiBusinessIpcHandlers') }));
vi.mock('../music/providers/qishuiAudio', () => ({ cleanupQishuiAudioSources: leaf('cleanupQishuiAudioSources'), handleQishuiAudioRequest: leaf('handleQishuiAudioRequest') }));
vi.mock('../ipc/system/hotkey', () => ({ registerHotkeyIpcHandlers: leaf('registerHotkeyIpcHandlers') }));
vi.mock('../ipc/settings/island', () => ({ registerIslandIpcHandlers: leaf('registerIslandIpcHandlers') }));
vi.mock('../ipc/system/hideProcess', () => ({ registerHideProcessIpcHandlers: leaf('registerHideProcessIpcHandlers') }));
vi.mock('../ipc/settings/theme', () => ({ registerThemeIpcHandlers: leaf('registerThemeIpcHandlers') }));
vi.mock('../ipc/window/window', () => ({ registerWindowIpcHandlers: leaf('registerWindowIpcHandlers'), toggleMousePassthroughLock: leaf('toggleMousePassthroughLock') }));
vi.mock('../ipc/media/media', () => ({ registerMediaIpcHandlers: leaf('registerMediaIpcHandlers') }));
vi.mock('../utils/broadcast', () => ({ broadcastSettingChange: leaf('broadcastSettingChange'), registerSettingsPreviewHandler: leaf('registerSettingsPreviewHandler') }));
vi.mock('../services/appLifecycle', () => ({ registerAppLifecycleHandlers: leaf('registerAppLifecycleHandlers') }));
vi.mock('../services/chromiumFlags', () => ({ applyChromiumPerformanceFlags: leaf('applyChromiumPerformanceFlags') }));
vi.mock('../services/hotkeyService', () => ({ createHotkeyService: factory('createHotkeyService', 'hotkeyService', ['getCurrentAgentVoiceInputHotkey', 'getCurrentHideHotkey', 'getCurrentNextSongHotkey', 'getCurrentOpenClipboardHistoryHotkey', 'getCurrentPlayPauseSongHotkey', 'getCurrentQuitHotkey', 'getCurrentResetPositionHotkey', 'getCurrentScreenshotHotkey', 'getCurrentShowSettingsWindowHotkey', 'getCurrentTogglePassthroughHotkey', 'getCurrentToggleShapeModeHotkey', 'getCurrentToggleTrayHotkey', 'getCurrentToggleUiLockHotkey', 'registerAgentVoiceInputHotkey', 'registerHideHotkey', 'registerNextSongHotkey', 'registerOpenClipboardHistoryHotkey', 'registerPlayPauseSongHotkey', 'registerQuitHotkey', 'registerResetPositionHotkey', 'registerScreenshotHotkey', 'registerShowSettingsWindowHotkey', 'registerTogglePassthroughHotkey', 'registerToggleShapeModeHotkey', 'registerToggleTrayHotkey', 'registerToggleUiLockHotkey', 'resumeIslandHotkeys', 'suspendIslandHotkeys']) }));
vi.mock('../services/updaterService', () => ({ initUpdaterService: leaf('initUpdaterService') }));
vi.mock('../window/captureWindow', () => ({ createCaptureWindowService: factory('createCaptureWindowService', 'captureWindowService', ['closeCaptureWindow', 'getCaptureWindow', 'startRegionScreenshot']) }));
vi.mock('../window/mainWindow', () => ({ createMainWindowService: factory('createMainWindowService', 'mainWindowService', ['applyIslandPositionOffset', 'createWindow', 'getInitialCenterX', 'notifyShapeModeChanged']) }));
vi.mock('../window/standaloneWindow', () => ({ openStandaloneWindow: leaf('openStandaloneWindow') }));
vi.mock('../window/splashWindow', () => ({ showSplashWindow: leaf('showSplashWindow'), closeSplashWindow: leaf('closeSplashWindow') }));
vi.mock('../window/guideWindow', () => ({ showGuideWindow: leaf('showGuideWindow') }));
vi.mock('../music/smtcService', () => ({ createSmtcService: factory('createSmtcService', 'smtcService', ['cleanupWorker', 'clearPendingSourceSwitchEntry', 'detectAllSources', 'getCurrentDeviceId', 'getPendingSourceSwitchEntry', 'getPendingSourceSwitchId', 'getSmtcSessionRuntime', 'initWorker', 'isWhitelisted', 'setCurrentDeviceId', 'setPendingSourceSwitchId']) }));
vi.mock('../music/smtcAccessor', () => ({ setSmtcAccessor: leaf('setSmtcAccessor') }));
vi.mock('../system/autoHideWatcher', () => ({ createAutoHideWatcher: factory('createAutoHideWatcher', 'autoHideWatcher', ['checkNow', 'getAutoHideFullscreenWindows', 'getConfiguredHideWindowTitleList', 'setAutoHideFullscreenWindows', 'setAutoHideWindowTitleList', 'setConfiguredHideWindowTitleList', 'setHiddenByAutoHideProcess', 'start', 'stop']) }));
vi.mock('../system/externalAgentWatcher', () => ({ createExternalAgentWatcher: factory('createExternalAgentWatcher', 'externalAgentWatcher', ['start', 'stop']) }));
vi.mock('../system/claudeCodeStatusService', () => ({ createClaudeCodeStatusService: factory('createClaudeCodeStatusService', 'claudeCodeStatusService', ['start', 'stop']) }));
vi.mock('../system/codexStatusService', () => ({ createCodexStatusService: factory('createCodexStatusService', 'codexStatusService', ['start', 'stop']) }));
vi.mock('@eisland/windows-smtc-helper', () => ({ play: leaf('play'), pause: leaf('pause'), next: leaf('next') }));
vi.mock('../system/runningProcesses', () => ({ queryFocusedWindow: leaf('queryFocusedWindow'), queryOpenWindowsWithIcons: leaf('queryOpenWindowsWithIcons'), queryRunningNonSystemProcessNames: leaf('queryRunningNonSystemProcessNames'), queryRunningNonSystemProcessesWithIcons: leaf('queryRunningNonSystemProcessesWithIcons'), sanitizeProcessNameList: leaf('sanitizeProcessNameList') }));

beforeEach(() => {
  vi.resetModules(); vi.clearAllMocks(); vi.useFakeTimers(); mocks.events.clear(); mocks.handlers.clear(); mocks.protocols.clear(); mocks.boot = undefined; mocks.windows = []; mocks.modeFiles.clear(); mocks.runtime.clear(); mocks.lock = true; mocks.packaged = true; mocks.firstLaunch = false; mocks.startupAnimation = true; mocks.whitelist = true;
  mocks.main = Object.assign(windowMock(), { getBounds: vi.fn(() => ({ x: 0, y: 0, width: 260, height: 42 })) });
  platform('win32');
  vi.spyOn(console, 'warn').mockImplementation(() => undefined); vi.spyOn(console, 'error').mockImplementation(() => undefined);
  leaf('app.getPath').mockImplementation((name) => name === 'downloads' ? 'C:/isolated-downloads' : 'C:/isolated-user-data'); leaf('app.getAppPath').mockReturnValue('C:/isolated-app'); leaf('app.getVersion').mockReturnValue('1.2.3');
  leaf('existsSync').mockReturnValue(true); leaf('readFileSync').mockImplementation((path) => { const key = String(path).split(/[\\/]/).at(-1)
    ?.replace('.json', ''); if (!key || !mocks.modeFiles.has(key)) throw new Error('not configured'); return JSON.stringify(mocks.modeFiles.get(key)); }); leaf('writeFileSync').mockReturnValue(undefined); leaf('mkdirSync').mockReturnValue(undefined);
  leaf('readFirstLaunchConfig').mockImplementation(() => mocks.firstLaunch); leaf('readStartupAnimationEnabledConfig').mockImplementation(() => mocks.startupAnimation);
  leaf('readWhitelistConfig').mockReturnValue(['custom.exe']); leaf('readSmtcUnsubscribeMsConfig').mockReturnValue(1234); leaf('readHideProcessListConfig').mockReturnValue(['Hidden']); leaf('readAutoHideFullscreenWindowsConfig').mockReturnValue(true); leaf('readIslandPositionOffsetConfig').mockReturnValue({ x: 4, y: 5 }); leaf('readIslandDisplaySelectionConfig').mockReturnValue('2'); leaf('readClipboardUrlMonitorEnabledConfig').mockReturnValue(true); leaf('readClipboardUrlDetectModeConfig').mockReturnValue('https-only'); leaf('readClipboardUrlBlacklistConfig').mockReturnValue(['example.com']); leaf('readUpdateAutoPromptConfig').mockReturnValue(false); leaf('readIslandShapeModeConfig').mockReturnValue('notch');
  ['readHotkeyConfig','readQuitHotkeyConfig','readScreenshotHotkeyConfig','readNextSongHotkeyConfig','readPlayPauseSongHotkeyConfig','readResetPositionHotkeyConfig','readToggleTrayHotkeyConfig','readShowSettingsWindowHotkeyConfig','readOpenClipboardHistoryHotkeyConfig','readTogglePassthroughHotkeyConfig','readToggleUiLockHotkeyConfig','readAgentVoiceInputHotkeyConfig','readToggleShapeModeHotkeyConfig'].forEach((name) => leaf(name).mockReturnValue(`configured:${name}`));
  leaf('mainWindowService.createWindow').mockImplementation(() => call(options('createMainWindowService'), 'setMainWindow', mocks.main));
  leaf('smtcService.isWhitelisted').mockImplementation(() => mocks.whitelist); leaf('smtcService.getSmtcSessionRuntime').mockImplementation(() => mocks.runtime); leaf('smtcService.getCurrentDeviceId').mockReturnValue('device');
  leaf('captureWindowService.startRegionScreenshot').mockResolvedValue(undefined); leaf('closeSplashWindow').mockResolvedValue(undefined); leaf('showGuideWindow').mockResolvedValue(undefined); leaf('cleanupQishuiAudioSources').mockResolvedValue(undefined); leaf('disposeLocalOcrWorker').mockResolvedValue(undefined);
  leaf('BrowserWindow.getAllWindows').mockReturnValue([]); leaf('net.fetch').mockResolvedValue(new Response('media')); leaf('handleAlbumMediaRequest').mockResolvedValue(new Response('album'));
  const display = { bounds: { x: -1920, y: 0, width: 1920, height: 1080 } }; leaf('screen.getDisplayMatching').mockReturnValue(display); leaf('screen.getPrimaryDisplay').mockReturnValue(display);
  leaf('nativeRequire').mockReturnValue(undefined);
  mocks.functions.forEach((fn, name) => { if (name.startsWith('hotkeyService.getCurrent')) fn.mockReturnValue(''); });
  const nativeMock = (request: string): unknown => { leaf('nativeRequire')(request); if (request === 'electron') return electron; if (request === '@eisland/windows-fullscreen-detector') return { isAnyFullscreenWindow: leaf('isAnyFullscreenWindow') }; throw new Error(`Unexpected native require: ${request}`); };
  vi.stubGlobal('require', nativeMock); const nativeModule = Module as unknown as { _load: (request: string, ...args: unknown[]) => unknown }; const original = nativeModule._load; vi.spyOn(nativeModule, '_load').mockImplementation((request, ...args) => ['electron', '@eisland/windows-fullscreen-detector'].includes(request) ? nativeMock(request) : original(request, ...args)); leaf('isAnyFullscreenWindow').mockReturnValue(false);
  leaf('createSessionMainLogger').mockReturnValue(leaf('writeMainLog')); leaf('clipboardUrlState.getMonitorEnabled').mockReturnValue(true); leaf('clipboardUrlState.getDetectMode').mockReturnValue('https-only'); leaf('clipboardUrlState.getBlacklist').mockReturnValue(['example.com']);
});
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); vi.unstubAllGlobals(); });
async function load(ready = true) { await import('../index'); expect(mocks.boot).toBeTypeOf('function'); if (ready) mocks.boot!(); }
async function media(url: string): Promise<Response> { return await mocks.protocols.get('eisland-media')!({ url }) as Response; }

describe('main entry boot and dependency wiring', () => {
  it('requests the instance lock and pre-registers flags/protocol privileges before readiness', async () => { mocks.lock = false; await load(false); expect(leaf('app.quit')).toHaveBeenCalledOnce(); expect(leaf('applyChromiumPerformanceFlags')).toHaveBeenCalledWith(electron.app); expect(leaf('protocol.registerSchemesAsPrivileged')).toHaveBeenCalledWith([{ scheme: 'eisland-media', privileges: { standard: true, secure: true, corsEnabled: true, supportFetchAPI: true, stream: true } }, { scheme: 'eisland-qishui', privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } }]); expect(leaf('mainWindowService.createWindow')).not.toHaveBeenCalled(); expect(leaf('registerAppLifecycleHandlers')).toHaveBeenCalledOnce(); });
  it.each(['win32', 'darwin', 'linux'])('boots safely on %s and limits OS polling to Windows', async (system) => { platform(system); await load(); expect(leaf('app.quit')).not.toHaveBeenCalled(); expect(leaf('setAppUserModelId')).toHaveBeenCalledWith('com.eisland.app'); expect(leaf('mainWindowService.createWindow')).toHaveBeenCalledOnce(); expect(leaf('createTray')).toHaveBeenCalledWith(mocks.main); expect(leaf('smtcService.initWorker')).toHaveBeenCalledOnce(); expect(leaf('setSmtcAccessor')).toHaveBeenCalledWith(leaf('smtcService.getSmtcSessionRuntime'), leaf('smtcService.getCurrentDeviceId')); expect(leaf('claudeCodeStatusService.start')).toHaveBeenCalledOnce(); expect(leaf('codexStatusService.start')).toHaveBeenCalledOnce(); expect(leaf('autoHideWatcher.start')).toHaveBeenCalledTimes(system === 'win32' ? 1 : 0); expect(leaf('externalAgentWatcher.start')).toHaveBeenCalledTimes(system === 'win32' ? 1 : 0); expect(leaf('autoHideWatcher.setAutoHideWindowTitleList')).toHaveBeenCalledWith(['Hidden']); expect(leaf('autoHideWatcher.setAutoHideFullscreenWindows')).toHaveBeenCalledWith(true); });
  it.each([true, false])('respects startup animation=%s', async (enabled) => { mocks.startupAnimation = enabled; await load(); expect(leaf('showSplashWindow')).toHaveBeenCalledTimes(enabled ? 1 : 0); expect(leaf('mainWindowService.createWindow')).toHaveBeenCalledOnce(); });
  it.each([{ firstLaunch: true, packaged: true, show: true, write: true }, { firstLaunch: false, packaged: true, show: false, write: false }, { firstLaunch: false, packaged: false, show: true, write: false }])('shows guide for first=$firstLaunch packaged=$packaged', async ({ firstLaunch, packaged, show, write }) => { mocks.firstLaunch = firstLaunch; mocks.packaged = packaged; await load(); await call(options('createMainWindowService'), 'onReadyToShow'); expect(leaf('closeSplashWindow')).toHaveBeenCalledOnce(); expect(leaf('showGuideWindow')).toHaveBeenCalledTimes(show ? 1 : 0); expect(leaf('writeFirstLaunchConfig')).toHaveBeenCalledTimes(write ? 1 : 0); if (show) expect(leaf('closeSplashWindow').mock.invocationCallOrder[0]).toBeLessThan(leaf('showGuideWindow').mock.invocationCallOrder[0]); if (write) { await call(options('createMainWindowService'), 'onReadyToShow'); expect(leaf('showGuideWindow')).toHaveBeenCalledOnce(); expect(leaf('writeFirstLaunchConfig')).toHaveBeenCalledOnce(); } });
  it('waits for guide completion before writing the first-launch marker', async () => { mocks.firstLaunch = true; let finish: () => void = () => undefined; leaf('showGuideWindow').mockImplementation(() => new Promise<void>((resolveGuide) => { finish = resolveGuide; })); await load(); const pending = call(options('createMainWindowService'), 'onReadyToShow'); await Promise.resolve(); expect(leaf('writeFirstLaunchConfig')).not.toHaveBeenCalled(); finish(); await pending; expect(leaf('writeFirstLaunchConfig')).toHaveBeenCalledOnce(); });
  it('registers all IPC leaves and supplies shared logger/updater/download configuration', async () => { await load(); const registrations = [...mocks.functions.entries()].filter(([name]) => /^register.*IpcHandlers$/.test(name)); expect(registrations.length).toBeGreaterThan(20); registrations.forEach(([name, fn]) => { expect(fn, name).toHaveBeenCalledOnce(); }); expect(leaf('registerNetIpcHandlers')).toHaveBeenCalledWith({ writeMainLog: leaf('writeMainLog') }); expect(leaf('registerLogIpcHandlers')).toHaveBeenCalledWith({ writeMainLog: leaf('writeMainLog') }); expect(options('registerMailIpcHandlers')).toEqual({ storeDir: join('C:/isolated-user-data', 'eIsland_store'), mailConfigStoreKey: 'mail-account-config' }); expect(call(options('registerUpdaterIpcHandlers'), 'getVersion')).toBe('1.2.3'); expect(call(options('registerUpdaterIpcHandlers'), 'isPackaged')).toBe(true); expect(call(options('registerDownloadIpcHandlers'), 'getDownloadsPath')).toBe('C:/isolated-downloads'); const updater = options('initUpdaterService'); expect(updater.autoCheckDelayMs).toBe(5000); expect(call(updater, 'getMainWindow')).toBe(mocks.main); expect(call(updater, 'getAppPath')).toBe('C:/isolated-app'); expect(call(updater, 'shouldAutoPromptUpdate')).toBe(false); });
  it('connects runtime getters/setters and keeps later IPC changes visible to services', async () => { await load(); const main = options('createMainWindowService'); const windowIpc = options('registerWindowIpcHandlers'); expect(call(main, 'getIslandPositionOffset')).toEqual({ x: 4, y: 5 }); expect(call(main, 'getIslandDisplaySelection')).toBe('2'); call(main, 'setIslandPositionOffset', { x: 11, y: 12 }); call(windowIpc, 'setIslandDisplaySelection', '9'); expect(call(windowIpc, 'getIslandPositionOffset')).toEqual({ x: 11, y: 12 }); expect(call(main, 'getIslandDisplaySelection')).toBe('9'); expect(call(windowIpc, 'getIslandDisplaySelection')).toBe('9'); const music = options('registerMusicIpcHandlers'); const smtc = options('createSmtcService'); expect(call(smtc, 'getWhitelist')).toEqual(['custom.exe']); expect(call(smtc, 'getSmtcUnsubscribeMs')).toBe(1234); call(music, 'setWhitelist', ['new.exe']); call(music, 'setSmtcUnsubscribeMs', 3000); expect(call(smtc, 'getWhitelist')).toEqual(['new.exe']); expect(call(smtc, 'getSmtcUnsubscribeMs')).toBe(3000); call(options('registerIslandIpcHandlers'), 'onShapeModeChanged'); expect(leaf('mainWindowService.notifyShapeModeChanged')).toHaveBeenCalledOnce(); });
  it('connects clipboard watcher start/stop callbacks with the same runtime state accessors', async () => { await load(); expect(leaf('clipboardUrlState.setMonitorEnabled')).toHaveBeenCalledWith(true); expect(leaf('clipboardUrlState.setDetectMode')).toHaveBeenCalledWith('https-only'); expect(leaf('clipboardUrlState.setBlacklist')).toHaveBeenCalledWith(['example.com']); const clipboard = options('registerClipboardIpcHandlers'); call(clipboard, 'startWatcher'); expect(leaf('startClipboardUrlWatcher')).toHaveBeenCalledTimes(2); const watcher = options('startClipboardUrlWatcher'); expect(call(watcher, 'getWindow')).toBe(mocks.main); expect(watcher.getEnabled).toBe(leaf('clipboardUrlState.getMonitorEnabled')); expect(watcher.getDetectMode).toBe(leaf('clipboardUrlState.getDetectMode')); expect(watcher.getBlacklist).toBe(leaf('clipboardUrlState.getBlacklist')); call(clipboard, 'stopWatcher'); expect(leaf('stopClipboardUrlWatcher')).toHaveBeenCalledOnce(); });
  it('registers configured hotkeys and leaves empty optional bindings unregistered', async () => { const optional = ['Quit','Screenshot','NextSong','PlayPauseSong','ResetPosition','ToggleTray','ShowSettingsWindow','OpenClipboardHistory','TogglePassthrough','ToggleUiLock','AgentVoiceInput','ToggleShapeMode']; optional.forEach((prefix) => leaf(`read${prefix}HotkeyConfig`).mockReturnValue('')); await load(); expect(leaf('hotkeyService.registerHideHotkey')).toHaveBeenCalledWith('configured:readHotkeyConfig'); optional.forEach((prefix) => expect(leaf(`hotkeyService.register${prefix}Hotkey`)).not.toHaveBeenCalled()); });
  it('recreates the main window on activation only when no windows remain', async () => { await load(); leaf('BrowserWindow.getAllWindows').mockReturnValue([mocks.main]); mocks.events.get('activate')!(); expect(leaf('mainWindowService.createWindow')).toHaveBeenCalledOnce(); leaf('BrowserWindow.getAllWindows').mockReturnValue([]); mocks.events.get('activate')!(); expect(leaf('mainWindowService.createWindow')).toHaveBeenCalledTimes(2); });
  it.each([{ key: 'F11', code: 'Other', blocked: true }, { key: 'Other', code: 'F11', blocked: true }, { key: 'F10', code: 'F10', blocked: false }])('handles F11 guard key=$key code=$code', async ({ key, code, blocked }) => { await load(); const win = windowMock(); mocks.events.get('browser-window-created')!({}, win); expect(leaf('watchWindowShortcuts')).toHaveBeenCalledWith(win); const preventDefault = vi.fn(); win.webContents.emit('before-input-event', { preventDefault }, { key, code }); expect(preventDefault).toHaveBeenCalledTimes(blocked ? 1 : 0); });
});

describe('main entry media protocol', () => {
  it('delegates album and qishui requests to their dedicated handlers', async () => { await load(); const request = { url: 'eisland-media://album/video.mp4', headers: { Range: 'bytes=1-9' } }; const response = await mocks.protocols.get('eisland-media')!(request) as Response; expect(await response.text()).toBe('album'); expect(leaf('handleAlbumMediaRequest')).toHaveBeenCalledWith(request); expect(mocks.protocols.get('eisland-qishui')).toBe(leaf('handleQishuiAudioRequest')); expect(leaf('net.fetch')).not.toHaveBeenCalled(); });
  it.each(['https://example.com', 'eisland-media://local', 'eisland-media://local/%E0%A4%A'])('rejects malformed request %s with 400', async (url) => { await load(); expect((await media(url)).status).toBe(400); expect(leaf('net.fetch')).not.toHaveBeenCalled(); });
  it.each([join('C:/isolated-user-data', 'secret.mp4'), join('C:/isolated-user-data', 'wallpapers-evil', 'video.mp4'), join('C:/isolated-user-data', 'wallpapers', '..', 'secret.mp4')])('denies file outside wallpaper directory %s', async (path) => { await load(); expect((await media(`eisland-media://local/${encodeURIComponent(path)}`)).status).toBe(403); expect(leaf('net.fetch')).not.toHaveBeenCalled(); });
  it('returns 404 for an allowed but missing file', async () => { await load(); leaf('existsSync').mockReturnValue(false); const path = join('C:/isolated-user-data', 'wallpapers', 'missing.mp4'); expect((await media(`eisland-media://local/${encodeURIComponent(path)}`)).status).toBe(404); expect(leaf('net.fetch')).not.toHaveBeenCalled(); });
  it.each(['local/', '/'])('streams allowed media with prefix=%s and ignores raw query/fragment', async (prefix) => { await load(); const path = join('C:/isolated-user-data', 'wallpapers', 'clip #1.mp4'); const response = await media(`eisland-media://${prefix}${encodeURIComponent(path)}?cache=1#frame`); expect(await response.text()).toBe('media'); expect(leaf('existsSync')).toHaveBeenCalledWith(resolve(path)); expect(leaf('net.fetch')).toHaveBeenCalledWith(pathToFileURL(resolve(path)).toString()); });
  it('returns 400 when path validation encounters I/O failure', async () => { await load(); const failure = new Error('FS unavailable'); leaf('existsSync').mockImplementation(() => { throw failure; }); const path = join('C:/isolated-user-data', 'wallpapers', 'video.mp4'); expect((await media(`eisland-media://local/${encodeURIComponent(path)}`)).status).toBe(400); expect(console.error).toHaveBeenCalledWith('[eisland-media] handler error:', failure); });
});

describe('main entry exit lifecycle', () => {
  it('deduplicates before-quit cleanup and resumes exit only after audio cleanup finishes', async () => { let finish: () => void = () => undefined; leaf('cleanupQishuiAudioSources').mockImplementation(() => new Promise<void>((resolveCleanup) => { finish = resolveCleanup; })); await load(); const preventDefault = vi.fn(); const quit = mocks.events.get('before-quit')!; quit({ preventDefault }); quit({ preventDefault }); expect(preventDefault).toHaveBeenCalledTimes(2); expect(leaf('cleanupQishuiAudioSources')).toHaveBeenCalledOnce(); expect(leaf('app.quit')).not.toHaveBeenCalled(); finish(); await Promise.resolve(); expect(leaf('app.quit')).toHaveBeenCalledOnce(); quit({ preventDefault }); expect(preventDefault).toHaveBeenCalledTimes(2); expect(leaf('cleanupQishuiAudioSources')).toHaveBeenCalledOnce(); });
  it('logs audio cleanup rejection and still resumes exit', async () => { const failure = new Error('cleanup failed'); leaf('cleanupQishuiAudioSources').mockRejectedValue(failure); await load(); mocks.events.get('before-quit')!({ preventDefault: vi.fn() }); await Promise.resolve(); expect(console.error).toHaveBeenCalledWith('[Qishui] Audio cleanup failed:', failure); expect(leaf('app.quit')).toHaveBeenCalledOnce(); });
  it('cleans watcher, status, worker, tray and shortcuts on will-quit', async () => { await load(); const lifecycle = options('registerAppLifecycleHandlers'); expect(call(lifecycle, 'getMainWindow')).toBe(mocks.main); call(lifecycle, 'onWillQuit'); ['autoHideWatcher.stop','externalAgentWatcher.stop','claudeCodeStatusService.stop','codexStatusService.stop','stopClipboardUrlWatcher','smtcService.cleanupWorker','disposeLocalOcrWorker','destroyTray','globalShortcut.unregisterAll'].forEach((name) => expect(leaf(name)).toHaveBeenCalledOnce()); });
  it.each(['win32', 'darwin', 'linux'])('cleans window-all-closed state and respects %s app lifecycle', async (system) => { platform(system); await load(); call(options('registerAppLifecycleHandlers'), 'onWindowAllClosed'); ['autoHideWatcher.stop','externalAgentWatcher.stop','smtcService.cleanupWorker','destroyTray'].forEach((name) => expect(leaf(name)).toHaveBeenCalledOnce()); expect(leaf('app.quit')).toHaveBeenCalledTimes(system === 'darwin' ? 0 : 1); });
});

describe('main entry hotkey callbacks and overlay guards', () => {
  it('guards next-song by whitelist and chooses playback command from runtime state', async () => { await load(); const hotkeys = options('createHotkeyService'); mocks.whitelist = false; call(hotkeys, 'onNextSongHotkey'); expect(leaf('next')).not.toHaveBeenCalled(); mocks.whitelist = true; call(hotkeys, 'onNextSongHotkey'); expect(leaf('next')).toHaveBeenCalledOnce(); call(hotkeys, 'onPlayPauseSongHotkey'); expect(leaf('play')).toHaveBeenCalledOnce(); mocks.runtime.set('device', { payload: { isPlaying: true } }); call(hotkeys, 'onPlayPauseSongHotkey'); expect(leaf('pause')).toHaveBeenCalledOnce(); });
  it('forwards reset/tray/passthrough/UI lock and shape toggle callbacks', async () => { await load(); const hotkeys = options('createHotkeyService'); call(hotkeys, 'onResetPositionHotkey'); expect(leaf('mainWindowService.applyIslandPositionOffset')).toHaveBeenCalledWith({ x: 0, y: 0 }); expect(leaf('writeIslandPositionOffsetConfig')).toHaveBeenCalledWith({ x: 0, y: 0 }); call(hotkeys, 'onToggleTrayHotkey'); expect(leaf('toggleTray')).toHaveBeenCalledOnce(); call(hotkeys, 'onTogglePassthroughHotkey'); const [[getMain]] = leaf('toggleMousePassthroughLock').mock.calls; expect((getMain as () => unknown)()).toBe(mocks.main); call(hotkeys, 'onToggleUiLockHotkey'); expect(leaf('broadcastSettingChange')).toHaveBeenCalledWith(-1, 'shortcut:toggle-ui-lock', expect.any(Number)); call(hotkeys, 'onToggleShapeModeHotkey'); expect(leaf('writeIslandShapeModeConfig')).toHaveBeenCalledWith('pill'); leaf('readIslandShapeModeConfig').mockReturnValue('pill'); call(hotkeys, 'onToggleShapeModeHotkey'); expect(leaf('writeIslandShapeModeConfig')).toHaveBeenCalledWith('notch'); expect(leaf('mainWindowService.notifyShapeModeChanged')).toHaveBeenCalledTimes(2); });
  it('reports screenshot hotkey failure without throwing out of the callback', async () => { const failure = new Error('screenshot failed'); leaf('captureWindowService.startRegionScreenshot').mockRejectedValue(failure); await load(); call(options('createHotkeyService'), 'onScreenshotHotkey'); await Promise.resolve(); expect(console.error).toHaveBeenCalledWith('[Screenshot] hotkey trigger error:', failure); });
  it('opens clipboard history only for a live main window and reveals a hidden one', async () => { await load(); const hotkeys = options('createHotkeyService'); call(hotkeys, 'onOpenClipboardHistoryHotkey'); expect(mocks.main!.show).toHaveBeenCalledOnce(); expect(mocks.main!.setAlwaysOnTop).toHaveBeenCalledWith(true, 'screen-saver'); expect(leaf('broadcastSettingChange')).toHaveBeenCalledWith(-1, 'shortcut:open-clipboard-history', expect.any(Number)); mocks.main!.state.destroyed = true; leaf('broadcastSettingChange').mockClear(); call(hotkeys, 'onOpenClipboardHistoryHotkey'); expect(leaf('broadcastSettingChange')).not.toHaveBeenCalled(); call(options('createMainWindowService'), 'setMainWindow', null); call(hotkeys, 'onOpenClipboardHistoryHotkey'); expect(leaf('broadcastSettingChange')).not.toHaveBeenCalled(); });
  it('opens settings only in standalone mode, falls back to legacy mode and tolerates tab-write failure', async () => { await load(); const hotkeys = options('createHotkeyService'); call(hotkeys, 'onShowSettingsWindowHotkey'); expect(leaf('openStandaloneWindow')).not.toHaveBeenCalled(); mocks.modeFiles.set('countdown-window-mode', 'standalone'); leaf('writeFileSync').mockImplementation(() => { throw new Error('read-only'); }); call(hotkeys, 'onShowSettingsWindowHotkey'); expect(leaf('openStandaloneWindow')).toHaveBeenCalledOnce(); expect(leaf('broadcastSettingChange')).toHaveBeenCalledWith(-1, 'store:standalone-window-active-tab', 'settings'); expect(leaf('writeFileSync')).toHaveBeenCalledWith(join('C:/isolated-user-data', 'eIsland_store', 'standalone-window-active-tab.json'), JSON.stringify('settings', null, 2), 'utf-8'); });
  it('blocks voice overlay in expanded/max states and preserves replacement during old fade-out', async () => { await load(); const hotkeys = options('createHotkeyService'); mocks.main!.getBounds = () => ({ x: 0, y: 0, width: 860, height: 150 }); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); expect(mocks.windows).toHaveLength(0); mocks.main!.getBounds = () => ({ x: 0, y: 0, width: 860, height: 400 }); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); expect(mocks.windows).toHaveLength(0); mocks.main!.getBounds = () => ({ x: 0, y: 0, width: 260, height: 42 }); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); const [first] = mocks.windows; expect(first.setIgnoreMouseEvents).toHaveBeenCalledWith(true); expect(leaf('screen.getDisplayMatching')).toHaveBeenCalled(); first.emit('ready-to-show'); expect(first.show).toHaveBeenCalledOnce(); call(hotkeys, 'onAgentVoiceInputHotkeyRelease'); expect(first.webContents.executeJavaScript).toHaveBeenCalledWith('startFadeOut()'); expect(mocks.main!.webContents.send).toHaveBeenCalledWith('agent-voice-input:state', false); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); const [, replacement] = mocks.windows; first.emit('ready-to-show'); expect(first.show).toHaveBeenCalledOnce(); await vi.advanceTimersByTimeAsync(450); expect(first.close).toHaveBeenCalledOnce(); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); expect(mocks.windows).toHaveLength(2); expect(replacement.show).toHaveBeenCalledOnce(); });
  it('creates CLI glow on the primary display without main and reuses/replaces it safely', async () => { mocks.packaged = false; await load(); call(options('createMainWindowService'), 'setMainWindow', null); expect(mocks.handlers.get('cli-glow:show')!()).toBe(true); const [first] = mocks.windows; expect(leaf('screen.getPrimaryDisplay')).toHaveBeenCalled(); expect(first.loadFile.mock.calls[0][0]).toContain(join('src', 'renderer', 'html', 'DynamicIslandAibackground')); expect(first.show).not.toHaveBeenCalled(); first.emit('ready-to-show'); expect(first.show).toHaveBeenCalledOnce(); mocks.handlers.get('cli-glow:show')!(); expect(mocks.windows).toHaveLength(1); expect(first.show).toHaveBeenCalledTimes(2); expect(mocks.handlers.get('cli-glow:hide')!()).toBe(true); mocks.handlers.get('cli-glow:show')!(); const [, nextWindow] = mocks.windows; first.emit('ready-to-show'); await vi.advanceTimersByTimeAsync(450); expect(first.close).toHaveBeenCalledOnce(); mocks.handlers.get('cli-glow:show')!(); expect(mocks.windows).toHaveLength(2); expect(nextWindow.show).toHaveBeenCalledOnce(); });
});

describe('main entry remaining runtime adapters', () => {
  it('exposes every window getter and music runtime getter through the supplied adapters', async () => { await load(); ['createCaptureWindowService','createMainWindowService','createAutoHideWatcher','createExternalAgentWatcher','createClaudeCodeStatusService','createCodexStatusService','createSmtcService','createHotkeyService','registerWindowIpcHandlers','registerMediaIpcHandlers'].forEach((name) => expect(call(options(name), 'getMainWindow')).toBe(mocks.main)); const music = options('registerMusicIpcHandlers'); expect(call(music, 'getWhitelist')).toEqual(['custom.exe']); expect(call(music, 'getSmtcUnsubscribeMs')).toBe(1234); const updater = options('initUpdaterService'); expect(call(updater, 'isPackaged')).toBe(true); const clipboard = options('registerClipboardIpcHandlers'); call(clipboard, 'startWatcher'); const [, [watcher]] = leaf('startClipboardUrlWatcher').mock.calls; expect(call(watcher as OptionBag, 'getWindow')).toBe(mocks.main); });
  it('collects reserved hotkeys using persisted fallback and prefers active bindings when available', async () => { await load(); const optionsBag = options('registerScreenshotHotkeyIpcHandlers'); const pairs = [['Hide','Hotkey'],['Quit','QuitHotkey'],['NextSong','NextSongHotkey'],['PlayPauseSong','PlayPauseSongHotkey'],['ResetPosition','ResetPositionHotkey'],['ToggleTray','ToggleTrayHotkey'],['ShowSettingsWindow','ShowSettingsWindowHotkey'],['OpenClipboardHistory','OpenClipboardHistoryHotkey'],['ToggleUiLock','ToggleUiLockHotkey'],['AgentVoiceInput','AgentVoiceInputHotkey'],['ToggleShapeMode','ToggleShapeModeHotkey']]; expect(call(optionsBag, 'getReservedHotkeys')).toEqual(pairs.map((pair) => `configured:read${pair[1]}Config`)); pairs.forEach(([current]) => leaf(`hotkeyService.getCurrent${current}Hotkey`).mockReturnValue(`live:${current}`)); expect(call(optionsBag, 'getReservedHotkeys')).toEqual(pairs.map(([current]) => `live:${current}`)); });
  it('creates the store directory before registering IPC when it is absent', async () => { leaf('existsSync').mockReturnValue(false); await load(); expect(leaf('mkdirSync')).toHaveBeenCalledWith(join('C:/isolated-user-data', 'eIsland_store'), { recursive: true }); expect(leaf('mkdirSync').mock.invocationCallOrder[0]).toBeLessThan(leaf('registerStoreIpcHandlers').mock.invocationCallOrder[0]); });
  it.each(['linux', 'win32'])('evaluates fullscreen detector only on %s where supported', async (system) => { platform(system); await load(); const watcher = options('createAutoHideWatcher'); leaf('isAnyFullscreenWindow').mockReturnValue(true); expect(call(watcher, 'isAnyFullscreenWindow')).toBe(system === 'win32'); if (system === 'win32') { leaf('isAnyFullscreenWindow').mockReturnValue('truthy'); expect(call(watcher, 'isAnyFullscreenWindow')).toBe(false); expect(leaf('nativeRequire')).toHaveBeenCalledOnce(); expect(leaf('isAnyFullscreenWindow')).toHaveBeenCalledTimes(2); } else { expect(leaf('nativeRequire')).not.toHaveBeenCalled(); } });
  it('caches an unavailable fullscreen plugin and warns once', async () => { await load(); const failure = new Error('native plugin unavailable'); leaf('nativeRequire').mockImplementation((request) => { if (request === '@eisland/windows-fullscreen-detector') throw failure; }); const watcher = options('createAutoHideWatcher'); expect(call(watcher, 'isAnyFullscreenWindow')).toBe(false); expect(call(watcher, 'isAnyFullscreenWindow')).toBe(false); expect(console.warn).toHaveBeenCalledWith('[FullscreenDetector] unavailable:', failure); expect(leaf('nativeRequire')).toHaveBeenCalledOnce(); });
  it('does not re-show a visible main window for clipboard history', async () => { await load(); mocks.main!.state.visible = true; call(options('createHotkeyService'), 'onOpenClipboardHistoryHotkey'); expect(mocks.main!.show).not.toHaveBeenCalled(); expect(leaf('broadcastSettingChange')).toHaveBeenCalledWith(-1, 'shortcut:open-clipboard-history', expect.any(Number)); });
  it('rejects missing/non-string window modes and creates storage before opening standalone settings', async () => { await load(); const hotkeys = options('createHotkeyService'); const store = join('C:/isolated-user-data', 'eIsland_store'); leaf('existsSync').mockReturnValue(false); call(hotkeys, 'onShowSettingsWindowHotkey'); expect(leaf('openStandaloneWindow')).not.toHaveBeenCalled(); leaf('existsSync').mockImplementation((path) => path !== store); mocks.modeFiles.set('standalone-window-mode', 123); call(hotkeys, 'onShowSettingsWindowHotkey'); expect(leaf('openStandaloneWindow')).not.toHaveBeenCalled(); mocks.modeFiles.set('standalone-window-mode', 'standalone'); call(hotkeys, 'onShowSettingsWindowHotkey'); expect(leaf('mkdirSync')).toHaveBeenCalledWith(store, { recursive: true }); expect(leaf('openStandaloneWindow')).toHaveBeenCalledOnce(); });
  it('creates an unpackaged voice overlay on primary display when main is absent and ignores destroyed fade targets', async () => { mocks.packaged = false; await load(); call(options('createMainWindowService'), 'setMainWindow', null); const hotkeys = options('createHotkeyService'); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); const [voice] = mocks.windows; expect(leaf('screen.getPrimaryDisplay')).toHaveBeenCalled(); expect(voice.loadFile.mock.calls[0][0]).toContain(join('src', 'renderer', 'html', 'DynamicIslandAibackground')); voice.webContents.executeJavaScript.mockRejectedValue(new Error('renderer gone')); call(hotkeys, 'onAgentVoiceInputHotkeyRelease'); voice.close(); voice.emit('ready-to-show'); await vi.advanceTimersByTimeAsync(450); expect(voice.close).toHaveBeenCalledOnce(); expect(voice.show).not.toHaveBeenCalled(); call(hotkeys, 'onAgentVoiceInputHotkeyRelease'); expect(voice.webContents.executeJavaScript).toHaveBeenCalledOnce(); });
  it('ignores a destroyed main for voice overlay and sends no voice state to it', async () => { await load(); mocks.main!.state.destroyed = true; const hotkeys = options('createHotkeyService'); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); expect(leaf('screen.getPrimaryDisplay')).toHaveBeenCalled(); expect(mocks.main!.webContents.send).not.toHaveBeenCalled(); call(hotkeys, 'onAgentVoiceInputHotkeyRelease'); expect(mocks.main!.webContents.send).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(450); });
  it('uses packaged CLI media on the matching display and tolerates fading an externally closed window', async () => { await load(); mocks.handlers.get('cli-glow:hide')!(); mocks.handlers.get('cli-glow:show')!(); const [glow] = mocks.windows; expect(leaf('screen.getDisplayMatching')).toHaveBeenCalled(); expect(glow.loadFile.mock.calls[0][0]).toContain(join('renderer', 'html', 'DynamicIslandAibackground')); expect(mocks.main!.setAlwaysOnTop).toHaveBeenCalledWith(true, 'screen-saver'); glow.webContents.executeJavaScript.mockRejectedValue(new Error('renderer gone')); mocks.handlers.get('cli-glow:hide')!(); glow.close(); glow.emit('ready-to-show'); await vi.advanceTimersByTimeAsync(450); expect(glow.close).toHaveBeenCalledOnce(); expect(glow.show).not.toHaveBeenCalled(); mocks.handlers.get('cli-glow:hide')!(); expect(glow.webContents.executeJavaScript).toHaveBeenCalledOnce(); });
});

describe('main entry direct overlay closing', () => {
  it('clears each active overlay reference when it is externally closed', async () => {
    await load(); const hotkeys = options('createHotkeyService'); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); const [voice] = mocks.windows; voice.close(); call(hotkeys, 'onAgentVoiceInputHotkeyHold'); expect(mocks.windows).toHaveLength(2); expect(mocks.windows[1]).not.toBe(voice);
    mocks.handlers.get('cli-glow:show')!(); const [, , glow] = mocks.windows; glow.close(); mocks.handlers.get('cli-glow:show')!(); expect(mocks.windows).toHaveLength(4); expect(mocks.windows[3]).not.toBe(glow);
  });
});
