/*
 * eIsland - A sleek, Apple Dynamic Island inspired floating widget for Windows, built with Electron.
 * https://github.com/JNTMTMTM/eIsland
 *
 * Copyright (C) 2026 JNTMTMTM
 * Copyright (C) 2026 pyisland.com
 *
 * Original author: JNTMTMTM[](https://github.com/JNTMTMTM)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**
 * @file captureWindow.test.ts
 * @description 验证隔离截图窗口的显示器布局、引擎回退、主窗口隐藏恢复与失败清理。
 * @author 鸡哥
 */

import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createCaptureWindowService } from '../captureWindow';
import mockWindow from './windowMock';
import type { BrowserWindow, BrowserWindowConstructorOptions, Rectangle } from 'electron';
interface DisplayFixture { id: number; bounds: Rectangle; size: { width: number; height: number }; scaleFactor: number; }
interface SourceFixture { thumbnail: { toPNG: () => Buffer }; }
const mocks = vi.hoisted(() => ({ create: vi.fn<(options: BrowserWindowConstructorOptions) => ReturnType<typeof mockWindow>>(), dev: true, exists: vi.fn<(path: string) => boolean>(), appPath: vi.fn<() => string>(), primary: vi.fn<() => DisplayFixture>(), displays: [] as DisplayFixture[], dip: vi.fn<(window: unknown, bounds: Rectangle) => Rectangle>(), sources: vi.fn<(options: { types: string[]; thumbnailSize: { width: number; height: number } }) => Promise<SourceFixture[]>>(), nativePrimary: vi.fn<() => Buffer | null>(), nativeAll: vi.fn<() => Buffer | null>(), visible: vi.fn<() => unknown[]>(), engine: vi.fn<() => string>() }));
vi.mock('electron', () => ({ BrowserWindow: mocks.create, app: { getAppPath: mocks.appPath }, desktopCapturer: { getSources: mocks.sources }, screen: { getAllDisplays: () => mocks.displays, getPrimaryDisplay: mocks.primary, dipToScreenRect: mocks.dip } }));
vi.mock('@electron-toolkit/utils', () => ({ is: { get dev() { return mocks.dev; } } }));
vi.mock('fs', () => ({ existsSync: mocks.exists }));
vi.mock('../screenshotHelper', () => ({ capturePrimaryDisplayPng: mocks.nativePrimary, captureAllDisplaysPng: mocks.nativeAll, getVisibleWindows: mocks.visible }));
vi.mock('../../config/storeConfig', () => ({ readScreenshotEngineConfig: mocks.engine }));
function display(id: number, x = 0, y = 0, width = 1920, height = 1080, scaleFactor = 1): DisplayFixture { return { id, scaleFactor, bounds: { x, y, width, height }, size: { width, height } }; }
function setup(main: ReturnType<typeof mockWindow> | null = mockWindow()) { const capture = mockWindow(); function constructWindow() { return capture; } mocks.create.mockImplementation(constructWindow); const service = createCaptureWindowService({ getMainWindow: () => main as unknown as BrowserWindow | null }); return { main, capture, service }; }
beforeEach(() => {
  vi.resetAllMocks(); vi.useFakeTimers(); mocks.dev = true; mocks.displays = [display(1)]; mocks.primary.mockReturnValue(mocks.displays[0]); mocks.appPath.mockReturnValue('C:/mock-app'); mocks.exists.mockReturnValue(false); mocks.engine.mockReturnValue('plugin'); mocks.nativePrimary.mockReturnValue(Buffer.from('native-primary')); mocks.nativeAll.mockReturnValue(Buffer.from('native-all')); mocks.visible.mockReturnValue([{ hwnd: 'A', title: 'Example' }]); mocks.sources.mockResolvedValue([{ thumbnail: { toPNG: () => Buffer.from('js-primary') } }]); mocks.dip.mockImplementation((target, bounds) => { expect(target).toBeNull(); const scale = mocks.displays.find((item) => item.bounds === bounds)?.scaleFactor || 1; return { x: bounds.x * scale, y: bounds.y * scale, width: bounds.width * scale, height: bounds.height * scale }; });
  vi.stubGlobal('process', Object.assign(Object.create(process) as NodeJS.Process, { resourcesPath: 'C:/mock-resources' })); vi.spyOn(console, 'error').mockImplementation(() => undefined);
});
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); vi.unstubAllGlobals(); });
describe('captureWindow', () => {
  it('hides the main window before capture, stages the overlay and restores main on closing', async () => { const { main, capture, service } = setup(); main!.state.visible = true; expect(service.getCaptureWindow()).toBeNull(); await service.startRegionScreenshot(); expect(main!.hide).toHaveBeenCalledOnce(); expect(main!.listenerCount('hide')).toBe(0); expect(main!.hide.mock.invocationCallOrder[0]).toBeLessThan(mocks.nativePrimary.mock.invocationCallOrder[0]); expect(service.getCaptureWindow()).toBe(capture); expect(mocks.create.mock.calls[0][0]).toMatchObject({ x: 0, y: 0, width: 1920, height: 1080, show: false, opacity: 0, skipTaskbar: true }); expect(capture.setBounds).toHaveBeenCalledWith({ x: 0, y: 0, width: 1920, height: 1080 }); expect(capture.setIgnoreMouseEvents.mock.calls).toEqual([[true], [false]]); expect(capture.showInactive).toHaveBeenCalledOnce(); expect(capture.setOpacity).toHaveBeenCalledWith(1); expect(capture.focus).toHaveBeenCalledOnce(); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ imageBytes: Buffer.from('native-primary'), captureSource: 'plugin', scaleFactor: 1, displays: [{ id: 1, bounds: mocks.displays[0].bounds, physicalBounds: mocks.displays[0].bounds, scaleFactor: 1 }], physicalScreen: { x: 0, y: 0, width: 1920, height: 1080 }, visibleWindows: [{ hwnd: 'A', title: 'Example' }] })); service.closeCaptureWindow(); expect(capture.close).toHaveBeenCalledOnce(); expect(service.getCaptureWindow()).toBeNull(); expect(main!.show).toHaveBeenCalledOnce(); expect(main!.setAlwaysOnTop).toHaveBeenCalledWith(true, 'screen-saver'); service.closeCaptureWindow(); expect(capture.close).toHaveBeenCalledOnce(); });
  it('combines negative-coordinate monitors and their physical bounds using largest scale', async () => { mocks.displays = [display(1, -1280, -100, 1280, 1024, 1), display(2, 0, 0, 1920, 1080, 2)]; mocks.primary.mockReturnValue(mocks.displays[1]); const { capture, service } = setup(null); await service.startRegionScreenshot(); expect(mocks.nativeAll).toHaveBeenCalledOnce(); expect(mocks.nativePrimary).not.toHaveBeenCalled(); expect(mocks.sources).not.toHaveBeenCalled(); expect(capture.setBounds).toHaveBeenCalledWith({ x: -1280, y: -100, width: 3200, height: 1180 }); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ imageBytes: Buffer.from('native-all'), virtualScreen: { x: -1280, y: -100, width: 3200, height: 1180 }, physicalScreen: { x: -1280, y: -100, width: 5120, height: 2260 }, scaleFactor: 2 })); });
  it('falls back from all-monitor native capture to primary native capture', async () => { mocks.displays.push(display(2, -1920)); mocks.nativeAll.mockReturnValue(null); const { capture, service } = setup(null); await service.startRegionScreenshot(); expect(mocks.nativePrimary).toHaveBeenCalledOnce(); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ imageBytes: Buffer.from('native-primary'), captureSource: 'plugin' })); });
  it.each(['js', 'plugin'])('uses JS primary-screen capture for engine=%s when native data is unavailable', async (engine) => { mocks.engine.mockReturnValue(engine); mocks.nativePrimary.mockReturnValue(null); mocks.nativeAll.mockReturnValue(null); mocks.displays = [display(1, -100, 30, 801, 601, 1.25), display(2, 701)]; mocks.primary.mockReturnValue(mocks.displays[0]); const { capture, service } = setup(null); await service.startRegionScreenshot(); if (engine === 'js') { expect(mocks.nativeAll).not.toHaveBeenCalled(); expect(mocks.nativePrimary).not.toHaveBeenCalled(); } expect(mocks.sources).toHaveBeenCalledWith({ types: ['screen'], thumbnailSize: { width: 1001, height: 751 } }); expect(capture.setBounds).toHaveBeenCalledWith({ x: -100, y: 30, width: 801, height: 601 }); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ imageBytes: Buffer.from('js-primary'), virtualScreen: { x: -100, y: 30, width: 801, height: 601 }, captureSource: 'js', displays: [], physicalScreen: null, scaleFactor: 1.25 })); });
  it('uses scale 1 when the primary scale is zero', async () => { mocks.engine.mockReturnValue('js'); mocks.displays = [display(1, 0, 0, 800, 600, 0)]; mocks.primary.mockReturnValue(mocks.displays[0]); const { capture, service } = setup(null); await service.startRegionScreenshot(); expect(mocks.sources).toHaveBeenCalledWith({ types: ['screen'], thumbnailSize: { width: 800, height: 600 } }); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ scaleFactor: 1 })); });
  it.each(['absent', 'hidden', 'destroyed'] as const)('skips hide waiting for %s main window', async (state) => { const main = state === 'absent' ? null : mockWindow(); if (main) main.state.destroyed = state === 'destroyed'; const { service } = setup(main); await service.startRegionScreenshot(); if (main) expect(main.hide).not.toHaveBeenCalled(); expect(mocks.nativePrimary).toHaveBeenCalledOnce(); });
  it('continues after hide timeout and removes the outstanding listener', async () => { const main = mockWindow(); main.state.visible = true; main.hide.mockImplementation(() => undefined); const { service } = setup(main); const pending = service.startRegionScreenshot(); await vi.advanceTimersByTimeAsync(79); expect(mocks.nativePrimary).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(1); await pending; expect(main.listenerCount('hide')).toBe(0); expect(mocks.nativePrimary).toHaveBeenCalledOnce(); });
  it('does not start twice while screenshot capture is pending or overlay already exists', async () => { mocks.engine.mockReturnValue('js'); let resolveSources: (sources: SourceFixture[]) => void = () => undefined; mocks.sources.mockImplementation(() => new Promise((resolve) => { resolveSources = resolve; })); const { capture, service } = setup(null); const first = service.startRegionScreenshot(); await Promise.resolve(); await service.startRegionScreenshot(); expect(mocks.sources).toHaveBeenCalledOnce(); resolveSources([{ thumbnail: { toPNG: () => Buffer.from('js') } }]); await first; await service.startRegionScreenshot(); expect(mocks.create).toHaveBeenCalledOnce(); service.closeCaptureWindow(); const retry = service.startRegionScreenshot(); await Promise.resolve(); expect(mocks.sources).toHaveBeenCalledTimes(2); resolveSources([]); await retry; expect(capture.close).toHaveBeenCalledOnce(); });
  it('restores main and releases the start guard when no JS source exists', async () => { mocks.engine.mockReturnValue('js'); mocks.sources.mockResolvedValue([]); const { main, service } = setup(); await service.startRegionScreenshot(); expect(mocks.create).not.toHaveBeenCalled(); expect(service.getCaptureWindow()).toBeNull(); expect(main!.show).toHaveBeenCalledOnce(); expect(main!.setAlwaysOnTop).toHaveBeenCalledWith(true, 'screen-saver'); mocks.sources.mockResolvedValue([{ thumbnail: { toPNG: () => Buffer.from('retry') } }]); await service.startRegionScreenshot(); expect(mocks.create).toHaveBeenCalledOnce(); });
  it.each(['capture', 'load', 'send'] as const)('cleans up and allows retry after %s failure', async (phase) => { const failure = new Error(`${phase} failed`); const { main, capture, service } = setup(); if (phase === 'capture') { mocks.engine.mockReturnValue('js'); mocks.sources.mockRejectedValue(failure); } else if (phase === 'load') { capture.loadFile.mockRejectedValue(failure); } else { capture.webContents.send.mockImplementation(() => { throw failure; }); } await service.startRegionScreenshot(); expect(console.error).toHaveBeenCalledWith('[Screenshot] start error:', failure); expect(service.getCaptureWindow()).toBeNull(); expect(main!.show).toHaveBeenCalled(); expect(main!.setAlwaysOnTop).toHaveBeenCalledWith(true, 'screen-saver'); expect(capture.destroy).toHaveBeenCalledTimes(phase === 'capture' ? 0 : 1); mocks.sources.mockResolvedValue([{ thumbnail: { toPNG: () => Buffer.from('retry') } }]); const next = mockWindow(); function constructRetry() { return next; } mocks.create.mockImplementation(constructRetry); await service.startRegionScreenshot(); expect(service.getCaptureWindow()).toBe(next); });
  it('does not send an image after closing during page load', async () => { const { main, capture, service } = setup(); let resolveLoad: () => void = () => undefined; capture.loadFile.mockImplementation(() => new Promise((resolve) => { resolveLoad = resolve; })); const pending = service.startRegionScreenshot(); await Promise.resolve(); await Promise.resolve(); service.closeCaptureWindow(); resolveLoad(); await pending; expect(capture.webContents.send).not.toHaveBeenCalled(); expect(capture.focus).not.toHaveBeenCalled(); expect(main!.show).toHaveBeenCalledOnce(); });
  it('does not restore an absent or destroyed main window on closing', async () => { const main = mockWindow(); main.state.destroyed = true; const { capture, service } = setup(main); await service.startRegionScreenshot(); service.closeCaptureWindow(); expect(main.show).not.toHaveBeenCalled(); expect(capture.close).toHaveBeenCalledOnce(); });
  it.each(['first', 'app', 'fallback', 'packaged'] as const)('selects the %s capture HTML candidate', async (mode) => { mocks.dev = mode !== 'packaged'; const candidates = { first: join(process.cwd(), 'resources', 'capture.html'), app: join('C:/mock-app', 'resources', 'capture.html'), fallback: join(process.cwd(), 'resources', 'capture.html'), packaged: join('C:/mock-resources', 'capture.html') }; mocks.exists.mockImplementation((path) => ['first', 'app'].includes(mode) && path === candidates[mode]); const { capture, service } = setup(null); await service.startRegionScreenshot(); const expected = candidates[mode]; expect(capture.loadFile).toHaveBeenCalledWith(expected); if (mode === 'packaged') expect(mocks.exists).not.toHaveBeenCalled(); });
});

describe('captureWindow delayed hide and cleanup boundaries', () => {
  it('settles hide only once when its timeout runs after the hide event', async () => { const main = mockWindow(); main.state.visible = true; const { service } = setup(main); await service.startRegionScreenshot(); await vi.advanceTimersByTimeAsync(80); expect(mocks.nativePrimary).toHaveBeenCalledOnce(); expect(main.listenerCount('hide')).toBe(0); });
  it('allows a destroyed main to finish hide waiting without touching its listeners', async () => { const main = mockWindow(); main.state.visible = true; main.hide.mockImplementation(() => { main.state.destroyed = true; }); const { service } = setup(main); const pending = service.startRegionScreenshot(); await vi.advanceTimersByTimeAsync(80); await pending; expect(mocks.nativePrimary).toHaveBeenCalledOnce(); expect(main.show).not.toHaveBeenCalled(); });
  it('uses scale-one fallback for zero-scale entries in a multi-monitor layout', async () => { mocks.displays = [display(1, -800, 0, 800, 600, 0), display(2, 0, 0, 800, 600, 0)]; mocks.primary.mockReturnValue(mocks.displays[1]); const { capture, service } = setup(null); await service.startRegionScreenshot(); expect(capture.webContents.send).toHaveBeenCalledWith('capture-image', expect.objectContaining({ scaleFactor: 1 })); });
  it('skips restoring a main window destroyed during failed capture', async () => { const main = mockWindow(); mocks.engine.mockReturnValue('js'); mocks.sources.mockImplementation(() => { main.state.destroyed = true; return Promise.reject(new Error('capture failed')); }); const { service } = setup(main); await service.startRegionScreenshot(); expect(service.getCaptureWindow()).toBeNull(); expect(main.show).not.toHaveBeenCalled(); });
});
